name: zooper_flutter_logging
description: An extensible logging library which provides containers to implement custom logging logic fast 
version: 0.0.3
homepage: https://github.com/zooper-lib/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:

  zooper_flutter_core: ^0.0.2

  intl: ^0.17.0

  flutter:
    sdk: flutter

  sentry: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
